package:
  name: exopy_pulses
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') +
             ( '' if environ.get('GIT_DESCRIBE_NUMBER', '0')  == '0' else
              ('.post' + environ.get('GIT_DESCRIBE_NUMBER', '0' )
               )
              )}}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  preserve_egg_dir: True

requirements:
  build:
    - python
    - future
  run:
    - python
    - exopy >=0.1.0
    - numpy

test:
  imports:
    - exopy_pulses

about:
  home: https://github.com/Exopy/exopy_pulses
  license: BSD
  license_file: LICENSE
  summary: Pulse sequences generation for Exopy
